### ISSUE TITLE
Wrong characters sent

### ISSUE THREAD

**Issue by sebraa** [klamonte/qodem#2]
Qodem sends ISO-8859-1 characters even when configured as CP437.

Example: "ä" is U+E4, or ISO-8859-1 0xE4, or CP437 0x84.
Qodem sends 0xE4, which in CP437 is Σ (U+3A3) instead.

**Comment by klamonte** [comment]
Thanks for reporting this.

qodem's UI is currently UTF-8 all the time, and this does leave a function gap right here.  At the moment all it does is send the lower 8 bits to non-Unicode hosts.

I need some time to think of the best way to handle this.  Implicitly converting ISO-8859-1 from the keyboard to the 8-bit codepages also affects the translate tables, compose key, and half/full duplex.

**Comment by sebraa** [comment]
It might be better to convert the UTF-8 character produced by the keyboard to the target codepage. How does this affect half/full duplex?

From my understanding, the compose key on its own shouldn't send any character at all (since it is used to build a character). However, one UTF-8 character might resolve into multiple bytes (I'm thinking of ¼, which resolves into the "1/" and "4" characters on a VT52). I'm not sure how to handle this the best way.

Also, the VT52 should never send 8-bit codes. :-)

**Comment by klamonte** [comment]
Fundamentally what I need to do is better rationalize the layers and features that lie in the between raw network I/O, glyphs, encodings, and the user I/O.  Qmodem(tm) came up in a day when all of this was de facto decided by the VGA font, so it didn't care about encodings vs glyphs.  It only had to worry instead about modem settings (baud and 5/6/7/8 bits per byte) and it was perfectly acceptable (even desired) to splat garbage on the screen if those settings didn't line up.

I've started some design noodling in the worklog, beginning with the questions that I need to have good answers for.  In the end I want to have sane defaults that work for both the classic BBS users and modern Xterm needs.

Compose key should probably be renamed too.  X11 compose key behaves as you describe, but qodem's is more like the old DOS [Alt code](https://en.wikipedia.org/wiki/Alt_code): you put in either 8-bit decimal or 16-bit Unicode and it transmits that to the remote side.  However I do notice that it sends those bytes through the translate table rather than raw, and that might be the wrong thing to do.

**Comment by klamonte** [comment]
Just put a new Windows build / source tarball up on the main page.  It should be mapping a fair bit of the Unicode back to the target codepage now.

**Comment by klamonte** [comment]
1.0beta just released.  Closing this one, if you still see some problems on the current release let's work them out on a new issue.
