### ISSUE TITLE
RFE: Allow use of system libraries for bundled dependencies

### ISSUE THREAD

**Issue by hobbes1069** [klamonte/qodem#20]
I packaged the pre-1.0 release of qodem some time ago for Fedora and would like to update it but there are now several bundled libraries which are frowned upon.

I tried some basic unbundling of libcrypt and libminiupnpc but ran into the following error:

```
ggcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Werror=format-security -DQ_NO_NEWTERM -DQODEM_USE_SDL -DQ_UPNP -I/usr/include/miniupnpc -c -o source/netclient.o source/netclient.c
source/netclient.c: In function ‘upnp_init’:
source/netclient.c:448:55: warning: passing argument 6 of ‘upnpDiscover’ makes pointer from integer without a cast [-Wint-conversion]
     device_list = upnpDiscover(2000, NULL, NULL, 0, 0, 2, NULL);
                                                       ^
```

**Comment by klamonte** [comment]
Sure, I'll be glad to make life easier. :)

Which version of miniupnpc are you trying to link against?  They changed their API from 1.4 to 1.9, I will put some version checks in there so that Qodem can do the right thing by default.  An easy workaround if you need one right now is passing --disable-upnp to configure.

On cryptlib, it is more complicated...

My personal preference is that cryptlib by default be disabled for Linux distributions (--disable-ssh).  As a client, it is severely behind OpenSSH on cipher support such that it cannot connect to an out-of-the-box recent sshd (Qodem bug #6).  As a server it is also behind such that people connecting to a Qodem host will probably need to pass '-m hmac-md5' to their client.  Defaulting it off makes things safer even though Qodem host mode loses its only encrypted channel support.

Worse still, Debian believes that cryptlib is not open source due to OpenSSL copyright notices in some of its source files (https://www.debian-administration.org/users/dkg/weblog/74 http://permalink.gmane.org/gmane.comp.encryption.cryptlib/2532), they seem unlikely to ever include it as a library.  I'm not sure if its presence taints my own source releases in their eyes or not, if so I would have no problem shipping a separate cryptlib-free source tarball.

**Comment by hobbes1069** [comment]
Fedora has 1.9 on all supported releases but it looks like 2.0 has been released. I can follow up with the Fedora maintainer if that matters.

Thanks for the tip on cryptlib, that's the easiest solution. The practice on Fedora is just to remove the offending code during build unless it's REALLY objectionable (non-free or patent encumbered). We try to use canonical upstream sources whenever possible, I really don't understand the Debian method of repackaging all the source code for everything.

**Comment by klamonte** [comment]
@hobbes1069 The 1.0.0-dev branch now has two changes for you:

1. Logic in configure.ac to detect the system-provided miniupnpc, and a miniupnpc version check in netclient.c.  On my Debian Jessie dev box this is working OK now.  In my deb/rpm scripts here I am passing --disable-upnp to avoid the explicit Depends/Requires on the library, but I have no strong opinion either way on distros using this feature.

2. cryptlib is now disabled by default for the autoconf build.  I still pass --disable-ssh in my deb/rpm scripts here just to be very explicit.

Do these changes appropriately address your needs here?

**Comment by hobbes1069** [comment]
I'm not sure if there was a separate commit in between these 3 but I couldn't apply all three as patches but the one I needed, the first one, did apply fine so that takes care of the immediate need.

**Comment by klamonte** [comment]
Awesome.  I'll close this one for now.

Thanks for your feedback and help, let me know if you need anything else.
