### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by sebraa** [klamonte/qodem#4]
Sometimes qodem (I am using the alpha version) just segfaults. I have seen this behaviour on all Emulation settings, and also when using ZMODEM file transfer.

**Comment by klamonte** [comment]
The alpha version had quite a few segfaults that are fixed in the current git version.  I'll leave this open as a more convenient place to list the ones I found before and perhaps catch new ones, as the commit logs for these are split between the old Sourceforge CVS and the new github, with a massive code sweep in between.  The main ones are:

- Using built-in ssh support, dialing two ssh connections where it prompts for username/password would crash on the second one.  (A double-free in phonebook.)

- Crash in ANSI emulation on non-glibc platforms if "ESC [ ; H" was the first sequence seen.  (Failing to set the initial value of a pointer to 0.)

- Crash on non-glibc platforms that could happen anytime.  (Bug in Xwscdup().)

- Crash in dialer if DNS responds with an error.  (Continued to connect() when network was unavailable.)

- Crash in dialer if connect() call come backs immediately with no connection.  (Sequencing between dialer and netclient, lots of ways for it to fail.).

- Crash when creating a quicklearn file with (I think) local or cmdline connections.

- Crash in all file transfers on platforms that don't report small time differences.  (Divide by zero when computing cps.)

**Comment by klamonte** [comment]
I'm going to close this one out now.  The codebase is nearly stable again, I only have one significant new feature to put in.  I will address crashes on an individual basis as they come in.
