### ISSUE TITLE
mbed TLS to replace cryptlib

### ISSUE THREAD

**Issue by angrylemur** [klamonte/qodem#60]
I love qodem, and my organization wants to eventually incorporate it into an embedded project (ARM Cortex-M4) for a local console and remote terminal capabilities.  I'm trying to gauge the feasibility of that task.

SSL capability is important, but the GPL license of cryptlib is an issue.  In an embedded system, we will need to link Qodem code with the rest of our application.  I am wondering if we can **replace cryptlib with [mbed TLS](https://tls.mbed.org/)** which is open source under an Apache license.

In a month or two, I may have time to investigate/implement/test this myself...

**Comment by klamonte** [comment]
Thank you for this feature request.

cryptlib currently is in qodem for two features: 1) ssh host mode (*nix and Win32), and 2) ssh client (Win32 only).  The default build in the pending 1.0.0 release for *nix does not build or link to cryptlib, due to its "non-free" status as per Debian, and its poor support of current SSH algorithms.  I would love an alternative to cryptlib.  It is hard to debug, and has not stayed current with OpenSSH.  I could also add SSL as a separate protocol (client and host), with hooks for mbed or others.

OTOH it may be that you don't need to do much here.  Do you just need outgoing connections?  Could qodem be able to execute a binary via forkpty() to get that connection?  Or do you need qodem's host mode too (not recommended, it's very lightly tested)?

**Comment by angrylemur** [comment]
Oops, when I wrote "SSL", what I meant was "SSH" :)

Yes, I only really need outgoing connections.  Host mode isn't important, but may add interesting future capabilities for our project.

Forkpty() isn't an option in the conventional sense because we will be using an RTOS or bare metal for the foreseeable future.  We already have a minimal PDCurses port that should suffice.  However, we would have to figure out other integrations like filesystem, local console, UART access, etc... but I don't want to add too much scope creep to this issue.

Just thought mbed TLS was an interesting option given its licensing, it should [work on my target microcontroller](http://www.st.com/resource/en/user_manual/dm00105446.pdf), your current issues with cryptlib, and the fact that mbed TLS seems to be staying current as it's maintained by ARM and used in OpenVPN.

**Comment by klamonte** [comment]
This might be quite a bit easier than it used to be.  Looks like libssh2 support mbedtls now, and I have libssh2 support (client only) already from 1.0alpha.  I'll create a branch to re-integrate the libssh2 support.

**Comment by klamonte** [comment]
This branch brings back in the 1.0alpha libssh2 support.  Limitations:

* Client only, no host mode.
* Cannot be mixed-and-match with cryptlib.
* Currently it is using gcrypt for MD5 in netclient.c, this should be trivial to switch to something else.
* Needs to be linked to zlib.
* Needs more debugging.  It wasn't sending terminal resize events correctly, not sure what else is incomplete.
* No idea how easy/hard it will be to work on Windows.
* Must be built via 'make -f build/Makefile.generic'

...but it does connect out OK, and seems to be using mbedtls for it.
