### ISSUE TITLE
Arrow keys don't work for ANSI BBS

### ISSUE THREAD

**Issue by lholden** [klamonte/qodem#65]
Using the latest version of qodem (both from source and the released 1.0 binaries), the arrow keys do not seem to work correctly when connecting to an ANSI BBS. 

This was working correctly and without issue in qodem 0.3.2 (the version available in Fedora).

To replicate the issue, you can connect to a BBS running a recent version of Mystic (so for example... agency.bbs.geek.nz). Visit the message menu, and then use the Indexed Message Reader.

Using Qodem 1.0 pressing an arrow key closes the screen. In Qodem 0.3.2, NetRunner, and SyncTerm the arrow keys navigate between the different entries.

**Comment by klamonte** [comment]
Thank you for reporting this.  I will see if I can replicate it.  I don't have regular access to unfiltered Internet so it might be a few days.  A few things in the meantime that might help:

* Arrow keys should be producing "ESC[A" (up) "ESC[B" (down) and so on.  If they aren't doing that, there might be a macro defined for them either in ansy.key or default.key that is being transmitted instead.  These can be checked in the Alt-J key editor, or looking in ~/.qodem.

* If it isn't a macro or emulation bug, it might also be a telnet bug (I fixed some between 0.3.2 and 1.0 and might have borked something else).  If these BBSes offer alternative connection methods (rlogin, ssh) that might get you running correctly too.

**Comment by lholden** [comment]
It looks like it misbehaves when connecting to a BBS via telnet and not SSH. 

I am guessing this may very well be a telnet bug. I do connect to some BBSs that only support telnet, so I'd love to see this fixed. :D

**Comment by klamonte** [comment]
That's very helpful, thank you!

**Comment by klamonte** [comment]
I've done some wireshark and verified that qodem's telnet client is sending the right thing.  However, it appears that post_keystroke()'s single-byte write()'s is leading to single-byte TCP packet payloads, causing mystic to bail out on its ANSI parser after reading the first ESC without the rest of the "[A" sequence handy.  mystic ought to instead do what ncurses does and use a timeout value for assuming a bare ESC is not part of a sequence: this behavior could also kill arrow keys for other connection methods such as dialup.  Arrow keys do appear to work on the synchronet I tested against.

That said, I can still make this better:

* Add qodem_write_buffered() and qodem_write_buffered_flush() so that post_keystroke() can accumulate the entire sequence before sending anything to telnet_write().  This should reduce by a lot the likelihood of splitting a sequence into several read()'s on the other end, regardless of connection method.  (Even when using external telnet.)  This will also improve the situation for Win32 that cannot fallback to external telnet.

* Followup with g00r00 on the mystic side.  Perhaps there is something he can do for mystic users, or correct me if this is not quite the right diagnosis.

**Comment by lholden** [comment]
Thank you for digging into this further klamonte! Both options sound very reasonable. 

If there is anything I can do to help, please let me know.

**Comment by klamonte** [comment]
The 1.0.0-dev branch now has code to buffer the outbound keystrokes.  It appears to work for me, does it work for you?

**Comment by lholden** [comment]
That branch does indeed seem to fix things! I did notice another bug related to using the internel telnet... but I'll make a new ticket for it as it's happening in the release branch too and seems somewhat unrelated.

**Comment by klamonte** [comment]
Awesome, thanks!  I'll leave this one open for a while to see if we get any other similar reports.  This weekend I might get opportunity to drop into Fido mystic and talk to g00r00.

**Comment by syrinxcultist** [comment]
I see where CMDLINE can be placed in the phonebook\entry but I'm new to qodem and don't know yet where to put the rest of these suggestions...

\\
It looks like it misbehaves when connecting to a BBS via telnet and not SSH. If I change the connect type to CMDLINE with the line to execute being: "telnet bbs.domain 23" things also seem to work correctly. Set the option in the config to use an external telnet and switched back the param to being just "bbs.domain" and it also still works correctly.
\\

where do you place 'the line to execute'?
set the option in the  config?

currently exploring qodem to try and figure this out on my own, but i thought i'd also ask for help ;)

**Comment by swolf154** [comment]
It's shame this software doesn't work with Mystic BBS. It's a real "cop-out" to blame Mystic BBS too. The arrows still don't work with Qodem and Mystic BBS. Get another telnet program. The author is not interested in fixing the problem.

**Comment by fadiaz** [comment]
This bug is still active.  And although I do not opt out the option of Mystic BBS doing something not normal, I also concur with previous user that just blaming Mystic BBS is the easy way out; since all other similar applications the arrow keys work.  It is a shame, since I really like very much Qodem and on all other features it is a Killer Terminal Application.  Really wish the developer would fix this.  Thanks.
