### ISSUE TITLE
Repeatable crash on Windows 10

### ISSUE THREAD

**Issue by geneb** [klamonte/qodem#84]
So here's a weird one for you...
I've got Qodem installed in my Windows 10 Enterprise Ed. (64 bit) system. The serial device I'm using is a TrendNet TU-S9 USB-Serial adapter. It appears as COM4.

I'd like to use it as the system console to an S-100 computer system. The weird thing is, turning the machine on or hitting its reset button will crash Qodem with no error dialog. It just goes away.

If I start Qodem after I've turned on the S-100 system, I can interact with its boot monitor without issue.

Is there some kind of crash log I could provide you folks to help debug this issue?

Tnx!

g.

**Comment by klamonte** [comment]
Thanks for reporting this.  Very interesting, and possibly related to #77.  I've been stuck on that one due to lack of a Windows machine with hardware serial port.  But since you are seeing it with a USB-to-serial adapter, I may have a path forward to debugging both of these issues.

In answer to your question: Qodem has debugging, but it must be enabled at compile time.  Most source files have lines like this:

```C
/* Set this to a not-NULL value to enable debug log. */
/* static const char * DLOGNAME = "ansi"; */
static const char * DLOGNAME = NULL;
```

Changing that to:

```C
/* Set this to a not-NULL value to enable debug log. */
static const char * DLOGNAME = "ansi";
// static const char * DLOGNAME = NULL;
```

...and recompiling will cause Qodem to create a file called "debug_qodem.txt" which will have source file specific messages included in it.  The file you would want to modify is qodem.c, which contains the I/O functions.  Likely what is happening is that qodem_read() (qodem.c around line 920) is either getting an error that I haven't seen before, or somehow I am corrupting memory or using the Windows comm API incorrectly.

...And the really bad news is that the Windows build of Qodem isn't the easiest thing to get going.  I am using Visual C++ 6 on a Win2k VM to build to ensure Qodem has the widest range of Windows machines to run on.

If you have access to a Linux machine to run Qodem on, debugging could be much faster and easier.  It's very interesting that Qodem's behavior depends on where the remote side's boot sequence is.  Wondering if this is a RS-232 thing (maybe a less common RTS/CTS/DSR/etc state), or actually dependent on the data transferred.

Thanks again for the report, I'm still moving into my place but hopefully will get a chance to look at these issues before the 1.0.1 release goes out.

**Comment by geneb** [comment]
If you want to share the VM privately, I'd be happy to spin it up here and try a build.  Barring that, I don't have the time to scratch build an environment, sorry. :(

I know that when I hit the reset on the S-100 box, it toggles the DCD.  I noticed that when using SyncTERM connected to the console port.  Could the DCD detection be the root issue here?  I can also dig into the CBIOS for the system to see if it's doing anything else to the console port besides toggling the DCD off and on.

g.

**Comment by klamonte** [comment]
Moving to GitLab...
